# Generate `lib/mascot-data.js`: the badge art inlined as data URIs.
#
# Why inline rather than serve the art from a route: the harness may load its GUI
# over http (DSH Desktop does) or over file:// (a static dist deployment). A
# route only works in the first, and the badge is precisely the thing that cannot
# be checked for a broken image by the test suite. Inlining removes the
# dependency entirely and makes the client bundle self-contained.
#
# Cost: the 320-pixel set is about 363 KB of PNG, ~484 KB once base64-encoded, in a
# bundle the harness serves from localhost and caches immutably. The first build
# embedded the 128-pixel set, which was fine for a 96-pixel badge and is not fine
# for a badge that renders up to 320: sampling 128 image pixels across 320 device
# pixels is what "too small to see clearly" actually was. Detail is the point of a
# character, so the largest derivative wins and the bytes are the price.
#
#   pwsh -File scripts/embed-mascot.ps1
#
# Re-run after replacing any derivative. `test/assets.test.mjs` asserts the
# generated file covers every state, so a forgotten re-run is caught.

[CmdletBinding()]
param(
  [string] $AssetDirectory = (Join-Path $PSScriptRoot '..\assets\mascot\320'),
  [string] $OutputFile = (Join-Path $PSScriptRoot '..\lib\mascot-data.js'),
  # The size whose art is embedded. 320 covers the largest size the badge renders,
  # at 1x, with nothing to spare — so a future size increase needs a new derivative
  # rather than a silent blur.
  [string] $Size = '320'
)

$ErrorActionPreference = 'Stop'

$assetDir = (Resolve-Path $AssetDirectory).Path
$states = @('idle', 'armed', 'held', 'released')

$entries = foreach ($state in $states) {
  $file = Join-Path $assetDir "$state.png"
  if (-not (Test-Path $file)) {
    throw "missing badge art: $file"
  }
  $bytes = [System.IO.File]::ReadAllBytes($file)
  $base64 = [System.Convert]::ToBase64String($bytes)
  [pscustomobject]@{
    State = $state
    Bytes = $bytes.Length
    Uri   = "data:image/png;base64,$base64"
  }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('/**')
$lines.Add(' * The badge art, inlined as data URIs.')
$lines.Add(' *')
$lines.Add(' * Generated by `scripts/embed-mascot.ps1` from `assets/mascot/' + $Size + '/`. Do not edit by hand.')
$lines.Add(' *')
$lines.Add(' * Inlined rather than served from a route because the harness may load its GUI')
$lines.Add(' * over http or over file://, and a route only reaches the first. A data URI makes')
$lines.Add(' * the client bundle self-contained, which matters most for the one artefact this')
$lines.Add(' * project cannot verify by itself: a broken image in a browser.')
$lines.Add(' *')
$lines.Add(' * @module peak-valley-brake/mascot-data')
$lines.Add(' */')
$lines.Add('')
$lines.Add('/**')
$lines.Add(' * Character art keyed by the published badge state.')
$lines.Add(' *')
$lines.Add(' * `idle` is the fallback: a state this build does not recognise still renders a')
$lines.Add(' * character rather than a blank corner.')
$lines.Add(' *')
$lines.Add(' * @type {Readonly<Record<string, string>>}')
$lines.Add(' */')
$lines.Add('export const MASCOT_ART = Object.freeze({')
foreach ($entry in $entries) {
  $lines.Add("  $($entry.State): '$($entry.Uri)',")
}
$lines.Add('});')
$lines.Add('')
$lines.Add('/** Pixel height of the inlined art, for laying out the badge before load. */')
$lines.Add("export const MASCOT_ART_HEIGHT = $Size;")
$lines.Add('')

Set-Content -Path $OutputFile -Value $lines -Encoding utf8NoBOM

$total = ($entries | Measure-Object -Property Bytes -Sum).Sum
Write-Host ("wrote {0}" -f (Resolve-Path $OutputFile).Path)
foreach ($entry in $entries) {
  Write-Host ("  {0,-10} {1,8:N0} bytes -> {2,8:N0} base64 chars" -f $entry.State, $entry.Bytes, $entry.Uri.Length)
}
Write-Host ("total PNG {0:N0} bytes; file {1:N0} bytes" -f $total, (Get-Item $OutputFile).Length)
